#!/usr/bin/env python3

import sqlite3
import glob
from datetime import datetime

# Get both databases
databases = sorted(glob.glob("dmr_capture_*.db"))
unenc_db = databases[-2]  # Radio 6969
enc_db = databases[-1]    # Radio 1234

print(f"Comparing MI patterns between:")
print(f"  Unencrypted: {unenc_db}")
print(f"  Encrypted: {enc_db}")

# Check the unencrypted database for any MI values
db_unenc = sqlite3.connect(unenc_db)
cursor_unenc = db_unenc.cursor()

cursor_unenc.execute("""
    SELECT COUNT(*), COUNT(DISTINCT h_mi), COUNT(DISTINCT c_mi)
    FROM superframes
    WHERE h_mi IS NOT NULL OR c_mi IS NOT NULL
""")

unenc_stats = cursor_unenc.fetchone()
print(f"\nUnencrypted DB MI stats: {unenc_stats}")

# Get the encrypted database MI pattern
db_enc = sqlite3.connect(enc_db)
cursor_enc = db_enc.cursor()

# Get the MI timeline
cursor_enc.execute("""
    SELECT id, start_timestamp, h_mi, c_mi, source_id, target_id
    FROM superframes
    WHERE h_mi IS NOT NULL OR c_mi IS NOT NULL
    ORDER BY start_timestamp
    LIMIT 20
""")

print("\nFirst 20 MI entries:")
print("ID   | Timestamp           | H-MI     | C-MI     | Source | Target")
print("-" * 60)

for row in cursor_enc.fetchall():
    sf_id, timestamp, h_mi, c_mi, source, target = row
    h_str = f"{h_mi:08X}" if h_mi else "--------"
    c_str = f"{c_mi:08X}" if c_mi else "--------"
    source_str = f"{source:6d}" if source is not None else "   N/A"
    target_str = f"{target:8d}" if target is not None else "     N/A"
    print(f"{sf_id:4d} | {timestamp} | {h_str} | {c_str} | {source_str} | {target_str}")

# Check for patterns in the MI values themselves
print("\n=== MI Value Analysis ===")

# Get all unique C-MI values
cursor_enc.execute("SELECT DISTINCT c_mi FROM superframes WHERE c_mi IS NOT NULL")
c_mi_values = [row[0] for row in cursor_enc.fetchall()]

print(f"\nTotal unique C-MI values: {len(c_mi_values)}")

# Look for mathematical relationships
print("\nChecking for patterns in C-MI values:")

# Sort C-MI values
c_mi_sorted = sorted(c_mi_values)

# Check differences between consecutive values
print("\nDifferences between consecutive C-MI values:")
for i in range(min(10, len(c_mi_sorted)-1)):
    diff = c_mi_sorted[i+1] - c_mi_sorted[i]
    print(f"  {c_mi_sorted[i]:08X} -> {c_mi_sorted[i+1]:08X}: diff = {diff:08X} ({diff})")

# Check bit patterns
print("\n\nBit pattern analysis:")
for i, c_mi in enumerate(c_mi_values[:5]):
    print(f"\nC-MI {i}: {c_mi:08X}")
    print(f"  Binary: {c_mi:032b}")
    print(f"  Bit count: {bin(c_mi).count('1')}")

# Check timing patterns
print("\n=== Timing Analysis ===")

cursor_enc.execute("""
    SELECT c_mi, MIN(start_timestamp) as first_seen, COUNT(*) as occurrences
    FROM superframes
    WHERE c_mi IS NOT NULL
    GROUP BY c_mi
    ORDER BY first_seen
    LIMIT 10
""")

print("\nC-MI appearance timing:")
prev_time = None
for c_mi, timestamp, count in cursor_enc.fetchall():
    if prev_time:
        time_obj = datetime.strptime(timestamp, '%Y-%m-%d %H:%M:%S')
        prev_obj = datetime.strptime(prev_time, '%Y-%m-%d %H:%M:%S')
        delta = (time_obj - prev_obj).total_seconds()
        print(f"{c_mi:08X}: {timestamp} ({count}x) - delta: {delta:.1f}s")
    else:
        print(f"{c_mi:08X}: {timestamp} ({count}x) - first")
    prev_time = timestamp

# Check if there's a relationship to frame numbers or counters
print("\n=== Frame Counter Correlation ===")

cursor_enc.execute("""
    SELECT sf.id, sf.c_mi, COUNT(a.id) as frame_count
    FROM superframes sf
    LEFT JOIN C_00000000_S0 a ON sf.id = a.superframe_id
    WHERE sf.c_mi IS NOT NULL
    GROUP BY sf.id
    LIMIT 10
""")

results = cursor_enc.fetchall()
if results:
    print("\nC-MI vs Frame count:")
    for sf_id, c_mi, frame_count in results:
        if c_mi:
            print(f"  SF {sf_id}: C-MI {c_mi:08X}, Frames: {frame_count}")

db_unenc.close()
db_enc.close()

print("\n=== Conclusions ===")
print("The C-MI values appear to be:")
print("1. Not based on LFSR progression from H-MI")
print("2. Not in the LFSR sequence at all") 
print("3. Possibly generated by a different algorithm")
print("4. May be related to timing or other parameters")