#!/usr/bin/env python3
"""
Explain the implications of fixed IVs for RC4 encryption
"""

print("=== RC4 ATTACK IMPLICATIONS ===\n")

print("What we know:")
print("1. H-MI is ALWAYS 0x6C8AB637 (fixed)")
print("2. C-MI follows a predictable LFSR sequence")
print("3. We can predict all future IVs with 100% accuracy")
print("\n")

print("How RC4 works in this system:")
print("1. Key = K (secret, we don't know this)")
print("2. IV = MI (H-MI or C-MI, which we CAN predict)")
print("3. RC4 initialization: RC4_Init(K || IV)")
print("4. Keystream = RC4_Generate()")
print("5. Ciphertext = Plaintext XOR Keystream")
print("\n")

print("CRITICAL VULNERABILITY:")
print("If we know ANY plaintext-ciphertext pair with a known IV,")
print("we can recover the keystream for that IV!")
print("\n")

print("Attack Method 1: Known-Plaintext Attack")
print("=" * 40)
print("If we have:")
print("  - Ciphertext C (captured from air)")
print("  - Plaintext P (known or guessed)")
print("  - IV (we always know this!)")
print("\nThen:")
print("  - Keystream = C XOR P")
print("  - We now have the complete keystream for this IV")
print("\n")

print("Attack Method 2: Two-Time Pad")
print("=" * 40)
print("If the same IV is used twice (which happens!):")
print("  - C1 = P1 XOR Keystream")
print("  - C2 = P2 XOR Keystream")
print("  - C1 XOR C2 = P1 XOR P2")
print("  - This reveals relationships between plaintexts")
print("\n")

print("What we can recover:")
print("=" * 40)
print("1. WITHOUT the key:")
print("   - Any plaintext IF we know some plaintext for that IV")
print("   - Statistical analysis of plaintexts")
print("   - Voice patterns (silence, repeated patterns)")
print("\n2. WITH partial known plaintext:")
print("   - Complete keystream for that IV")
print("   - All other plaintext encrypted with same IV")
print("   - Potentially the key itself (with enough data)")
print("\n")

print("Practical Impact:")
print("=" * 40)
print("1. IMMEDIATE: Decrypt any message if we know ANY plaintext")
print("   encrypted with the same IV (even partial)")
print("\n2. MEDIUM TERM: Build a database of IV->Keystream mappings")
print("   As we collect known plaintexts, we can decrypt future")
print("   messages using the same IVs")
print("\n3. LONG TERM: Potentially recover the secret key K")
print("   With enough IV/keystream pairs, cryptanalysis may")
print("   reveal the actual key")
print("\n")

print("DMR Specific Vulnerabilities:")
print("=" * 40)
print("1. Fixed H-MI means header keystream NEVER changes")
print("2. Limited C-MI cycle means keystreams repeat")
print("3. Predictable silence periods in voice")
print("4. Known protocol fields (headers, checksums)")
print("5. AMBE vocoder produces predictable patterns")
print("\n")

# Demonstrate with example
print("Example Attack:")
print("=" * 40)
print("1. Capture encrypted transmission with IV=0xE8083B57")
print("2. Identify silent period (AMBE produces known pattern)")
print("3. XOR ciphertext with known silence pattern")
print("4. Result: Keystream for IV=0xE8083B57")
print("5. Decrypt ALL future messages with this IV!")
print("\n")

print("CONCLUSION:")
print("This is a CATASTROPHIC vulnerability. The encryption is")
print("effectively broken because:")
print("- IVs are predictable")
print("- IVs repeat frequently")
print("- Known plaintext is common")
print("- No key recovery needed for decryption")